### ISSUE TITLE
Crash upon clicking checkbox next to KDE style in settings

### ISSUE THREAD

**Issue by foemre** [oskarsh/Yin-Yang#100]
Kubuntu 21.04
KDE version 5.21
I tried both installing PyQt5 from pip and building Qt 5.15.2 from source.

I receive the following upon clicking the checkbox next to KDE in this screen:

![image](https://user-images.githubusercontent.com/13662484/136179017-beac7b28-9609-4df4-aa34-563b95cf0175.png)

`lookandfeeltool: /tmp/_MEIQ0un0r/libQt5Core.so.5: version `Qt_5.15' not found (required by lookandfeeltool)
lookandfeeltool: /tmp/_MEIQ0un0r/libQt5Core.so.5: version `Qt_5.15' not found (required by /lib/x86_64-linux-gnu/libKF5KCMUtils.so.5)
lookandfeeltool: /tmp/_MEIQ0un0r/libQt5Core.so.5: version `Qt_5.15' not found (required by /lib/x86_64-linux-gnu/libKF5KDELibs4Support.so.5)
lookandfeeltool: /tmp/_MEIQ0un0r/libQt5Core.so.5: version `Qt_5.15' not found (required by /lib/x86_64-linux-gnu/libKF5QuickAddons.so.5)
lookandfeeltool: /tmp/_MEIQ0un0r/libQt5Core.so.5: version `Qt_5.15' not found (required by /lib/x86_64-linux-gnu/libkworkspace5.so.5)
lookandfeeltool: /tmp/_MEIQ0un0r/libQt5Core.so.5: version `Qt_5.15' not found (required by /lib/x86_64-linux-gnu/libKF5KIOGui.so.5)
lookandfeeltool: /tmp/_MEIQ0un0r/libQt5Core.so.5: version `Qt_5.15' not found (required by /lib/x86_64-linux-gnu/libKF5JobWidgets.so.5)
lookandfeeltool: /tmp/_MEIQ0un0r/libQt5Core.so.5: version `Qt_5.15' not found (required by /lib/x86_64-linux-gnu/libKF5Service.so.5)
lookandfeeltool: /tmp/_MEIQ0un0r/libQt5Core.so.5: version `Qt_5.15' not found (required by /lib/x86_64-linux-gnu/libKF5Package.so.5)
lookandfeeltool: /tmp/_MEIQ0un0r/libQt5Core.so.5: version `Qt_5.15' not found (required by /lib/x86_64-linux-gnu/libKF5IconThemes.so.5)
lookandfeeltool: /tmp/_MEIQ0un0r/libQt5Core.so.5: version `Qt_5.15' not found (required by /lib/x86_64-linux-gnu/libKF5ConfigWidgets.so.5)
lookandfeeltool: /tmp/_MEIQ0un0r/libQt5Core.so.5: version `Qt_5.15' not found (required by /lib/x86_64-linux-gnu/libKF5ConfigGui.so.5)
lookandfeeltool: /tmp/_MEIQ0un0r/libQt5Core.so.5: version `Qt_5.15' not found (required by /lib/x86_64-linux-gnu/libKF5CoreAddons.so.5)
lookandfeeltool: /tmp/_MEIQ0un0r/libQt5Core.so.5: version `Qt_5.15' not found (required by /lib/x86_64-linux-gnu/libKF5I18n.so.5)
lookandfeeltool: /tmp/_MEIQ0un0r/libQt5Core.so.5: version `Qt_5.15' not found (required by /lib/x86_64-linux-gnu/libKF5WindowSystem.so.5)
lookandfeeltool: /tmp/_MEIQ0un0r/libQt5Core.so.5: version `Qt_5.15' not found (required by /lib/x86_64-linux-gnu/libQt5X11Extras.so.5)
lookandfeeltool: /tmp/_MEIQ0un0r/libQt5Core.so.5: version `Qt_5.15' not found (required by /lib/x86_64-linux-gnu/libKF5ConfigCore.so.5)
lookandfeeltool: /tmp/_MEIQ0un0r/libQt5Core.so.5: version `Qt_5.15' not found (required by /lib/x86_64-linux-gnu/libQt5QuickWidgets.so.5)
lookandfeeltool: /tmp/_MEIQ0un0r/libQt5Core.so.5: version `Qt_5.15' not found (required by /lib/x86_64-linux-gnu/libKF5XmlGui.so.5)
lookandfeeltool: /tmp/_MEIQ0un0r/libQt5Core.so.5: version `Qt_5.15' not found (required by /lib/x86_64-linux-gnu/libKF5Declarative.so.5)
lookandfeeltool: /tmp/_MEIQ0un0r/libQt5Core.so.5: version `Qt_5.15' not found (required by /lib/x86_64-linux-gnu/libKF5Auth.so.5)
lookandfeeltool: /tmp/_MEIQ0un0r/libQt5Core.so.5: version `Qt_5.15' not found (required by /lib/x86_64-linux-gnu/libKF5AuthCore.so.5)
lookandfeeltool: /tmp/_MEIQ0un0r/libQt5Core.so.5: version `Qt_5.15' not found (required by /lib/x86_64-linux-gnu/libKF5GuiAddons.so.5)
lookandfeeltool: /tmp/_MEIQ0un0r/libQt5Core.so.5: version `Qt_5.15' not found (required by /lib/x86_64-linux-gnu/libKF5ItemViews.so.5)
lookandfeeltool: /tmp/_MEIQ0un0r/libQt5Core.so.5: version `Qt_5.15' not found (required by /lib/x86_64-linux-gnu/libKF5WidgetsAddons.so.5)
lookandfeeltool: /tmp/_MEIQ0un0r/libQt5Core.so.5: version `Qt_5.15' not found (required by /lib/x86_64-linux-gnu/libKF5KIOFileWidgets.so.5)
lookandfeeltool: /tmp/_MEIQ0un0r/libQt5Core.so.5: version `Qt_5.15' not found (required by /lib/x86_64-linux-gnu/libKF5Notifications.so.5)
lookandfeeltool: /tmp/_MEIQ0un0r/libQt5Core.so.5: version `Qt_5.15' not found (required by /lib/x86_64-linux-gnu/libKF5Parts.so.5)
lookandfeeltool: /tmp/_MEIQ0un0r/libQt5Core.so.5: version `Qt_5.15' not found (required by /lib/x86_64-linux-gnu/libKF5Solid.so.5)
lookandfeeltool: /tmp/_MEIQ0un0r/libQt5Core.so.5: version `Qt_5.15' not found (required by /lib/x86_64-linux-gnu/libKF5TextWidgets.so.5)
lookandfeeltool: /tmp/_MEIQ0un0r/libQt5Core.so.5: version `Qt_5.15' not found (required by /lib/x86_64-linux-gnu/libKF5KIOWidgets.so.5)
lookandfeeltool: /tmp/_MEIQ0un0r/libQt5Core.so.5: version `Qt_5.15' not found (required by /lib/x86_64-linux-gnu/libKF5Completion.so.5)
lookandfeeltool: /tmp/_MEIQ0un0r/libQt5Core.so.5: version `Qt_5.15' not found (required by /lib/x86_64-linux-gnu/libKF5KIOCore.so.5)
lookandfeeltool: /tmp/_MEIQ0un0r/libQt5Core.so.5: version `Qt_5.15' not found (required by /lib/x86_64-linux-gnu/libKF5Crash.so.5)
lookandfeeltool: /tmp/_MEIQ0un0r/libQt5Core.so.5: version `Qt_5.15' not found (required by /lib/x86_64-linux-gnu/libQt5PrintSupport.so.5)
lookandfeeltool: /tmp/_MEIQ0un0r/libQt5Core.so.5: version `Qt_5.15' not found (required by /lib/x86_64-linux-gnu/libKF5Codecs.so.5)
lookandfeeltool: /tmp/_MEIQ0un0r/libQt5Core.so.5: version `Qt_5.15' not found (required by /lib/x86_64-linux-gnu/libKF5GlobalAccel.so.5)
lookandfeeltool: /tmp/_MEIQ0un0r/libstdc++.so.6: version `GLIBCXX_3.4.28' not found (required by /lib/x86_64-linux-gnu/libQt5Xml.so.5)
lookandfeeltool: /tmp/_MEIQ0un0r/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /lib/x86_64-linux-gnu/libQt5Xml.so.5)
lookandfeeltool: /tmp/_MEIQ0un0r/libQt5Core.so.5: version `Qt_5.15' not found (required by /lib/x86_64-linux-gnu/libQt5Xml.so.5)
lookandfeeltool: /tmp/_MEIQ0un0r/libQt5Core.so.5: version `Qt_5.15' not found (required by /lib/x86_64-linux-gnu/libKF5DBusAddons.so.5)
lookandfeeltool: /tmp/_MEIQ0un0r/libQt5Core.so.5: version `Qt_5.15' not found (required by /lib/x86_64-linux-gnu/libKF5Archive.so.5)
lookandfeeltool: /tmp/_MEIQ0un0r/libQt5Core.so.5: version `Qt_5.15' not found (required by /lib/x86_64-linux-gnu/libKF5Attica.so.5)
lookandfeeltool: /tmp/_MEIQ0un0r/libQt5Core.so.5: version `Qt_5.15' not found (required by /lib/x86_64-linux-gnu/libKF5Bookmarks.so.5)
lookandfeeltool: /tmp/_MEIQ0un0r/libQt5Core.so.5: version `Qt_5.15' not found (required by /lib/x86_64-linux-gnu/libQt5TextToSpeech.so.5)
lookandfeeltool: /tmp/_MEIQ0un0r/libQt5Core.so.5: version `Qt_5.15' not found (required by /lib/x86_64-linux-gnu/libKF5SonnetUi.so.5)
lookandfeeltool: /tmp/_MEIQ0un0r/libQt5Core.so.5: version `Qt_5.15' not found (required by /lib/x86_64-linux-gnu/libKF5SonnetCore.so.5)
Traceback (most recent call last):
  File "/home/daeh/Application/Yin-Yang-Build/src/gui.py", line 147, in toggleKdeFields
  File "/home/daeh/Application/Yin-Yang-Build/src/gui.py", line 129, in getKdeThemes
  File "/usr/lib/python3.6/subprocess.py", line 336, in check_output
  File "/usr/lib/python3.6/subprocess.py", line 418, in run
subprocess.CalledProcessError: Command '['lookandfeeltool', '-l']' returned non-zero exit status 1.
Aborted (core dumped)`

**Comment by l0drex** [comment]
> This error is thrown by the command line application `lookandfeeltool`. Running it from the terminal should produce the same error.

Try installing Qt5 from your package manager

**Comment by quanta-kt** [comment]
I am experiencing the same problem

>  Running it from the terminal should produce the same error.

Running `lookandfeeltool -l` from terminal does not give me any errors.
Output:
```
$ lookandfeeltool -l                            
org.kde.breezetwilight.desktop
org.kde.breeze.desktop
org.kde.breezedark.desktop
```
