### ISSUE TITLE
"KeyError: 'KvFlatDark'" on Manjaro KDE

### ISSUE THREAD

**Issue by tsbarnes** [oskarsh/Yin-Yang#128]
I just installed this on Manjaro KDE (testing branch) and when I try to run `yin-yang` it crashes during `load_plugins` with this error:
```
Traceback (most recent call last):
  File "/opt/yin-yang/main.py", line 110, in <module>
    main()
  File "/opt/yin-yang/main.py", line 60, in main
    window = config_window.MainWindow()
  File "/opt/yin-yang/src/ui/config_window.py", line 29, in __init__
    self.load()
  File "/opt/yin-yang/src/ui/config_window.py", line 59, in load
    self.load_plugins()
  File "/opt/yin-yang/src/ui/config_window.py", line 120, in load_plugins
    plugin.available_themes[used_theme]
KeyError: 'KvFlatDark'
```

I'm using git revision b236e813e548cc2b0880b91250cc783d2c61e851 (tag: 3.0.1) and I'm on the latest Manjaro testing branch (last updated today, Sept. 27).

**Comment by l0drex** [comment]
Seems like the names changed: `KvFlatDark` is now just `KvFlat`. Fix is on the way

**Comment by l0drex** [comment]
Let me know if this fixes your issue
