### ISSUE TITLE
App instantly crashes after fresh install

### ISSUE THREAD

**Issue by JokaJukka** [oskarsh/Yin-Yang#131]
Hey there!
I was just trying out the v3.0.1 release, but after installation this happened:
```
2022-10-10 12:56:57,020 ERROR - __main__: Error while loading application translations!
Error while loading translation. Using default language.
Traceback (most recent call last):
  File "/opt/yin-yang/main.py", line 110, in <module>
    main()
  File "/opt/yin-yang/main.py", line 60, in main
    window = config_window.MainWindow()
  File "/opt/yin-yang/src/ui/config_window.py", line 29, in __init__
    self.load()
  File "/opt/yin-yang/src/ui/config_window.py", line 59, in load
    self.load_plugins()
  File "/opt/yin-yang/src/ui/config_window.py", line 89, in load_plugins
    widget = plugin.get_widget(self.ui.plugins_scroll_content)
  File "/opt/yin-yang/src/plugins/_plugin.py", line 73, in get_widget
    for inp in self.get_input(widget):
  File "/opt/yin-yang/src/plugins/_plugin.py", line 82, in get_input
    if self.available_themes != {}:
  File "/opt/yin-yang/src/plugins/vscode.py", line 109, in available_themes
    for theme_name in get_theme_name(f'{path}/{extension_dir}/package.json'):
  File "/opt/yin-yang/src/plugins/vscode.py", line 35, in get_theme_name
    if 'themes' in manifest['contributes']:
KeyError: 'contributes'
```

Any help would be appreciated!

**Comment by l0drex** [comment]
I think I fixed it, can you please try the current master branch?

**Comment by JokaJukka** [comment]
Yep, works just fine!

**Comment by not-AMM** [comment]
I'm having almost the same problem right now:
![image](https://user-images.githubusercontent.com/43765089/197655689-b4886252-a52e-465e-938b-1822ed9918e7.png)


I'm using openSUSE TW and KDE Plasma.

**Comment by JokaJukka** [comment]
You cropped the bottom part of the stacktrace. But from what I can tell, it is a different issue. I recommend you to create a new report.
