### ISSUE TITLE
vscode extension bug

### ISSUE THREAD

**Issue by cloudwindy** [oskarsh/Yin-Yang#134]
I had some left files from a old version of ms-python (ms-python.python-2021.2.582707922) which I uninstalled, and yin-yang exited with following output:
```
Using default configuration values.
2022-10-11 23:44:33,866 ERROR - __main__: Error while loading application translations!
Error while loading translation. Using default language.
Traceback (most recent call last):
  File "/opt/yin-yang/main.py", line 110, in <module>
    main()
  File "/opt/yin-yang/main.py", line 60, in main
    window = config_window.MainWindow()
  File "/opt/yin-yang/src/ui/config_window.py", line 29, in __init__
    self.load()
  File "/opt/yin-yang/src/ui/config_window.py", line 59, in load
    self.load_plugins()
  File "/opt/yin-yang/src/ui/config_window.py", line 89, in load_plugins
    widget = plugin.get_widget(self.ui.plugins_scroll_content)
  File "/opt/yin-yang/src/plugins/_plugin.py", line 73, in get_widget
    for inp in self.get_input(widget):
  File "/opt/yin-yang/src/plugins/_plugin.py", line 82, in get_input
    if self.available_themes != {}:
  File "/opt/yin-yang/src/plugins/vscode.py", line 112, in available_themes
    for theme_name in get_theme_name(f'{path}/{extension_dir}/package.json'):
  File "/opt/yin-yang/src/plugins/vscode.py", line 30, in get_theme_name
    with open(path, 'r') as file:
FileNotFoundError: [Errno 2] 没有那个文件或目录: '/home/skey/.vscode/extensions/ms-python.python-2021.2.582707922/package.json'
```

**Comment by l0drex** [comment]
This should work now, but please test and let me know!
