### ISSUE TITLE
VSCode themes change breaks Yin-Yang

### ISSUE THREAD

**Issue by chase9** [oskarsh/Yin-Yang#139]
I was unable to get Yin-Yang after updating from an older version. The issue was that it was unable to find the VSCode theme that was in my config. Deleting my config didn't help since the default one is also unavailable.

```
Error while updating old config file. No value found for system.enabled
Error while updating old config file. No value found for system.light_theme
Error while updating old config file. No value found for system.dark_theme
Error while updating old config file. No value found for notification.enabled
Error while updating old config file. No value found for notification.light_theme
Error while updating old config file. No value found for notification.dark_theme
/opt/yin-yang/main.py:65: DeprecationWarning: Function: 'QLibraryInfo.location(QLibraryInfo.LibraryPath location)' is marked as deprecated, please check the documentation for more information.
  path = QLibraryInfo.location(QLibraryInfo.TranslationsPath)
2022-10-31 08:27:40,233 ERROR - root: Error while loading application translations!
Error while loading translation. Using default language.
Traceback (most recent call last):
  File "/opt/yin-yang/main.py", line 107, in <module>
    main(args)
  File "/opt/yin-yang/main.py", line 84, in main
    window = main_window_connector.MainWindow()
  File "/opt/yin-yang/src/ui/main_window_connector.py", line 56, in __init__
    self.load()
  File "/opt/yin-yang/src/ui/main_window_connector.py", line 90, in load
    self.load_plugins()
  File "/opt/yin-yang/src/ui/main_window_connector.py", line 143, in load_plugins
    plugin.available_themes[used_theme]
KeyError: 'Default Light+'
```

I was able to get yin-yang running by setting the VSCode themes to an empty string. Upon launch, I noticed that there were only three options available for VSCode themes:
- PowerShell ISE
- Visual Studio 2019 Dark
- Visual Studio 2019 Light

**Comment by trigrab** [comment]
I have the same problem. I installed vscode via ubuntu packages from the microsoft repository.

How did you manage to set the theme to an empty string? I don't have my old config file anymore.

**Comment by trigrab** [comment]
I think I found the issue and created a PR
