### ISSUE TITLE
Error after uninstalling theme

### ISSUE THREAD

**Issue by JokaJukka** [oskarsh/Yin-Yang#149]
Hey there!
I've uninstalled a Materia theme from my KDE Plasma desktop, and now the app won't start. The following stacktrace is thrown:
```
Traceback (most recent call last):
  File "/opt/yin-yang/main.py", line 107, in <module>
    main(args)
  File "/opt/yin-yang/main.py", line 84, in main
    window = main_window_connector.MainWindow()
  File "/opt/yin-yang/src/ui/main_window_connector.py", line 56, in __init__
    self.load()
  File "/opt/yin-yang/src/ui/main_window_connector.py", line 90, in load
    self.load_plugins()
  File "/opt/yin-yang/src/ui/main_window_connector.py", line 120, in load_plugins
    widget = plugin.get_widget(self.ui.plugins_scroll_content)
  File "/opt/yin-yang/src/plugins/_plugin.py", line 76, in get_widget
    for inp in self.get_input(widget):
  File "/opt/yin-yang/src/plugins/_plugin.py", line 102, in get_input
    inp.setCurrentIndex(themes.index(self.available_themes[theme]))
KeyError: 'com.github.varlesh.materia-dark'
```

Running Arch Linux, latest KDE Plasma and Yin-Yang 3.2.0. The same thing happens when I uninstall any theme from any "plugin" - KDE, GTK, Kvantum...

**Comment by l0drex** [comment]
Should be fixed with the newest release
