### ISSUE TITLE
v3.2.4-beta.2 crashes after installation

### ISSUE THREAD

**Issue by maros-ross99** [oskarsh/Yin-Yang#194]
### Describe the bug

After following the steps:
```
python3 -m venv .venv
source .venv/bin/activate
# Install pip requirements
pip3 install -r requirements.txt
# Install Yin-Yang
./scripts/install.sh
```
the app was successfully installed but crashed on the very first run and keeps crashing every time it is run:
```
user@user-laptop:~$ yin-yang 
Traceback (most recent call last):
  File "/opt/yin-yang/main.py", line 13, in <module>
    from src import daemon_handler
  File "/opt/yin-yang/src/daemon_handler.py", line 7, in <module>
    from src.config import ConfigWatcher, config
  File "/opt/yin-yang/src/config.py", line 160, in <module>
    plugins = get_plugins(get_desktop())
  File "/opt/yin-yang/src/plugins/__init__.py", line 25, in get_plugins
    konsole.Konsole(),
  File "/opt/yin-yang/src/plugins/konsole.py", line 32, in __init__
    super().__init__()
  File "/opt/yin-yang/src/plugins/_plugin.py", line 19, in __init__
    self.theme_light = ''
  File "/opt/yin-yang/src/plugins/konsole.py", line 42, in theme_light
    self.update_profile(False, value)
  File "/opt/yin-yang/src/plugins/konsole.py", line 157, in update_profile
    self.create_profiles()
  File "/opt/yin-yang/src/plugins/konsole.py", line 172, in create_profiles
    copyfile(self.user_path / self.default_profile, light_profile)
TypeError: unsupported operand type(s) for /: 'PosixPath' and 'NoneType'
```
Disabling the Konsole plugin solved the issue, however the user is not able to benefit from the plugin.

### Enabled plugins
- [x] Atom
- [x] Brave
- [x] Colors
- [x] Custom Script
- [x] Firefox
- [x] Gedit
- [x] GTK
- [x] Konsole
- [x] Kvantum
- [x] Only Office
- [x] System
- [x] VSCode
- [x] Wallpaper

### Affected versions

- Yin-Yang version: v3.2.4-beta.2
- System: Kubuntu 22.04.1
- KDE Plasma Version: 5.24.7
- KDE Frameworks Version: 5.92.0
- Kernel Version: 5.19.0-40-generic (64-bit)
- Python version: Python 3.10.6
- Qt version: 5.15.3

**Comment by l0drex** [comment]
What is the content of `~/.config/konsolerc`? Is there a default profile setting like this:
```ini
[Desktop Entry]
DefaultProfile=Profilename.profile
```

**Comment by l0drex** [comment]
And also, what profiles do you have? These are files in `~/.local/share/konsole`.

**Comment by maros-ross99** [comment]
Apologies for a late response. Here's the content of `~/.config/konsolerc`:

```
[MainWindow]
HDMI-1 Height 1920x1080=636
HDMI-1 Height 3840x2160=458
HDMI-1 Width 1920x1080=1071
HDMI-1 Width 3840x2160=1108
HDMI-1 XPosition 1920x1080=424
HDMI-1 XPosition 3840x2160=2732
HDMI-1 YPosition 1920x1080=217
HDMI-1 YPosition 3840x2160=1658
RestorePositionForNextInstance=false
State=AAAA/wAAAAD9AAAAAQAAAAAAAAAAAAAAAPwCAAAAAfsAAAAcAFMAUwBIAE0AYQBuAGEAZwBlAHIARABvAGMAawAAAAAA/////wAAANUBAAADAAAELwAAAl4AAAAEAAAABAAAAAgAAAAI/AAAAAEAAAACAAAAAgAAABYAbQBhAGkAbgBUAG8AbwBsAEIAYQByAAAAAAD/////AAAAAAAAAAAAAAAcAHMAZQBzAHMAaQBvAG4AVABvAG8AbABiAGEAcgAAAAAA/////wAAAAAAAAAA
ToolBarsMovable=Disabled
eDP-1 HDMI-1 Height 1366x768=695
eDP-1 HDMI-1 Width 1366x768=1282
eDP-1 HDMI-1 XPosition 1366x768=84
eDP-1 HDMI-1 YPosition 1366x768=29
eDP-1 Height 1366x768=695
eDP-1 Width 1366x768=1282
eDP-1 XPosition 1366x768=84
eDP-1 YPosition 1366x768=73

[UiSettings]
ColorScheme=
WindowColorScheme=Default
```

I don't have any profiles under `~/.local/share/konsole`

**Comment by l0drex** [comment]
Then you need to create make sure a profile is created:
1. Open Konsole
2. Go to settings > Setup Konsole > Profiles (might have different names, I'm re-translating the german local)
3. Create a new profile and set it as your default.
