### ISSUE TITLE
Yin-Yang does not start

### ISSUE THREAD

**Issue by zsolt-donca** [oskarsh/Yin-Yang#215]
### Describe the bug

Yin-Yang does not start:

```
❯ yin-yang 
Using default configuration values.
Traceback (most recent call last):
  File "/opt/yin-yang/main.py", line 13, in <module>
    from src import daemon_handler
  File "/opt/yin-yang/src/daemon_handler.py", line 7, in <module>
    from src.config import ConfigWatcher, config
  File "/opt/yin-yang/src/config.py", line 474, in <module>
    config = ConfigManager()
             ^^^^^^^^^^^^^^^
  File "/opt/yin-yang/src/config.py", line 179, in __init__
    self.load()
  File "/opt/yin-yang/src/config.py", line 247, in load
    pl.theme_dark = config_loaded['plugins'][pl.name.lower()]['dark_theme']
    ^^^^^^^^^^^^^
  File "/opt/yin-yang/src/plugins/konsole.py", line 51, in theme_dark
    self.update_profile(True, value)
  File "/opt/yin-yang/src/plugins/konsole.py", line 179, in update_profile
    profile_config['Appearance']['ColorScheme'] = theme
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/configparser.py", line 979, in __getitem__
    raise KeyError(key)
KeyError: 'Appearance'
```

### Enabled plugins

Clean install, removed `~/.config/yin_yang`.

### Affected versions

- Yin-Yang version:

- Relevant application version: [yin-yang](https://aur.archlinux.org/packages/yin-yang), version 3.2.4-1, and also happens with [yin-yang-git](https://aur.archlinux.org/packages/yin-yang-git)
- Python version: 3.11.5
- Qt version: 6.5.2

### Additional notes

Running Arch Linux. Already tried rebuilding [python-suntime](https://aur.archlinux.org/packages/python-suntime).

**Comment by sashaaaaaaaaa** [comment]
duplicate bug: #200

Basically you need to create Konsole themes called "Light" and "Dark" and set a color theme for them in the Appearance settings.
