### ISSUE TITLE
Loss qt6-positioning and python-suntime on Arch Linux

### ISSUE THREAD

**Issue by iHad168** [oskarsh/Yin-Yang#249]
### Describe the bug
Loss qt6-positioning and python-suntime on Arch Linux

### Enabled plugins
- [ ] KDE

### Affected versions
- Yin-Yang version:

- Relevant application version[^1]: 3.3
- Python version:3.11.6
- Qt version: 5, 6

### Additional notes
```
╭─localhost@localhost in ~
╰─λ yin-yang
Traceback (most recent call last):
File "<frozen runpy>", line 198, in _run_module_as_main
File "<frozen runpy>", line 88, in _run_code
File "/opt/yin-yang/yin_yang/main.py", line 16, in <module>
from yin_yang import daemon_handler
File "/opt/yin-yang/yin_yang/daemon_handler.py", line 7, in <module>
from .config import ConfigWatcher, config
File "/opt/yin-yang/yin_yang/config.py", line 13, in <module>
from PySide6.QtPositioning import QGeoPositionInfoSource, QGeoPositionInfo, QGeoCoordinate
ImportError: libQt6Positioning.so.6: cannot open shared object file: No such file or directory
```

```
╭─localhost@localhost in ~ took 296ms
[🔴] × yin-yang
Traceback (most recent call last):
File "<frozen runpy>", line 198, in _run_module_as_main
File "<frozen runpy>", line 88, in _run_code
File "/opt/yin-yang/yin_yang/main.py", line 16, in <module>
from yin_yang import daemon_handler
File "/opt/yin-yang/yin_yang/daemon_handler.py", line 7, in <module>
from .config import ConfigWatcher, config
File "/opt/yin-yang/yin_yang/config.py", line 15, in <module>
from suntime import Sun, SunTimeException
ModuleNotFoundError: No module named 'suntime'
```

**Comment by l0drex** [comment]
Well you need to have the `suntime' package installed. Either with pip or through the aur.

**Comment by mreilaender** [comment]
For the second error, you have to rebuilt the package `python-suntime` (see [this comment](https://aur.archlinux.org/packages/python-suntime#comment-971177)
