### ISSUE TITLE
`PySide6.QtDBus.QDBusMessage` is not deepcopyable 

### ISSUE THREAD

**Issue by w568w** [oskarsh/Yin-Yang#277]
### What happened?

When a `DBusPlugin` (e.g. `_Budgie`, `_Kde`) calls `DBusPlugin.create_message`, an error occurs at:

https://github.com/oskarsh/Yin-Yang/blob/f72bfff78a964bd6c63e7c3d5f800bd551c4e4a5/yin_yang/plugins/_plugin.py#L271-L274

---

`QDBusMessage` does implement `__copy__`. But as the [documentation](https://doc.qt.io/qtforpython-6/PySide6/QtDBus/QDBusMessage.html#PySide6.QtDBus.PySide6.QtDBus.QDBusMessage) says, 

> [QDBusMessage](https://doc.qt.io/qtforpython-6/PySide6/QtDBus/QDBusMessage.html#PySide6.QtDBus.PySide6.QtDBus.QDBusMessage) objects are shared. Modifications made to the copy will affect the original one as well.

So it might be better to change `base_message` to `base_message_factory` (or `base_message_creator`)?

### Version

Build from master (f72bfff78a964bd6c63e7c3d5f800bd551c4e4a5)

### How did you install Yin & Yang?

AUR

### What desktop environments are you seeing the problem on?

KDE

### Which plugin causes the issue?

GTK

### What software version do you use?

n/a

### Relevant log output

```shell
Exception in thread GTK:
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/yin-yang/yin_yang/plugins/_plugin.py", line 56, in set_mode
    self.set_theme(theme)
  File "/opt/yin-yang/yin_yang/plugins/_plugin.py", line 208, in set_theme
    self.strategy.set_theme(theme)
  File "/opt/yin-yang/yin_yang/plugins/gtk.py", line 96, in set_theme
    response = self.call(self.create_message(theme))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/yin-yang/yin_yang/plugins/_plugin.py", line 272, in create_message
    message = copy.deepcopy(self.base_message)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/copy.py", line 161, in deepcopy
    rv = reductor(4)
         ^^^^^^^^^^^
TypeError: cannot pickle 'PySide6.QtDBus.QDBusMessage' object
```

**Comment by cheanus** [comment]
Same log output and error on Arch, KDE 6
