### ISSUE TITLE
Kvantumanager not found in Arch Budgie

### ISSUE THREAD

**Issue by WinnerWind** [oskarsh/Yin-Yang#294]
### What happened?

When running Yin & Yang from the terminal using `yin-yang` this error comes up

```
Plugin Colors has no support for your desktop environment yet!
Using default configuration values.
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/opt/yin-yang/yin_yang/__main__.py", line 16, in <module>
    from yin_yang import daemon_handler
  File "/opt/yin-yang/yin_yang/daemon_handler.py", line 7, in <module>
    from .config import ConfigWatcher, config
  File "/opt/yin-yang/yin_yang/config.py", line 482, in <module>
    for pl in filter(lambda pl: pl.available, plugins):
  File "/opt/yin-yang/yin_yang/config.py", line 482, in <lambda>
    for pl in filter(lambda pl: pl.available, plugins):
                                ^^^^^^^^^^^^
  File "/opt/yin-yang/yin_yang/plugins/_plugin.py", line 167, in available
    return self.check_command([self.command[0], '--help'])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/yin-yang/yin_yang/plugins/_plugin.py", line 156, in check_command
    subprocess.check_call(command, stdout=subprocess.DEVNULL)
  File "/usr/lib/python3.11/subprocess.py", line 408, in check_call
    retcode = call(*popenargs, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 389, in call
    with Popen(*popenargs, **kwargs) as p:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.11/subprocess.py", line 1953, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: 'kvantummanager'
```
When running it with sudo, the window appears which should not happen as the root user has no installed desktop environment. Also, none of the settings work. Changing the settings gives the error
`Failed to connect to bus: No medium found`

The repo says that it is supported with Budgie however i have no idea why it is not working.

### Version

3.3

### How did you install Yin & Yang?

AUR

### What desktop environments are you seeing the problem on?

other :  Budgie for Arch Linux

### Which plugin causes the issue?

None

### What software version do you use?

OS: Arch Linux x86_64  DE: Budgie 10.9.1

**Comment by l0drex** [comment]
Looks like yin yang can't execute `kvantummanager --help`. Make sure its executable as a normal user.

> `Failed to connect to bus: No medium found`

That I have never seen. Which plugins are active? Looks like it's related to the dbus.

**Comment by WinnerWind** [comment]
You're right @l0drex ! I don't have `kvantumanager` nor can I find where it is.
I don't know what you mean by plugins, sorry! I just clicked the Light/Dark button and this error popped up (when run as `sudo`)

**Comment by WinnerWind** [comment]
Switching the themes after installing kvantum now throws the following error
```
Plugin Colors has no support for your desktop environment yet!
Error while loading translation. Using default language.
Exception in thread Wallpaper:
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/yin-yang/yin_yang/plugins/_plugin.py", line 56, in set_mode
    self.set_theme(theme)
  File "/opt/yin-yang/yin_yang/plugins/_plugin.py", line 200, in set_theme
    raise ValueError(f'Theme \"{theme}\" is invalid')
ValueError: Theme "" is invalid
```

**Comment by l0drex** [comment]
Oh, so you don't use kvantum? Then you don't need it. Thought you had it installed and yin yang couldn't use it. I'm in the middle of the woods right now, will take a look in the next days

**Comment by WinnerWind** [comment]
I don't use Kvantum. No idea what it is to be fair. From first glance it just seems like another theming tool like GTK or KDE (as if that combination wasn't complicated enough!)
But knowing that it's not needed I'll uninstall it. No idea why the application requested for it.

**Comment by l0drex** [comment]
Its kind of a theme manager for qt (kde) themes, like an alternative to breeze
