### ISSUE TITLE
  Wallpaper change failed

### ISSUE THREAD

**Issue by Buschi03** [oskarsh/Yin-Yang#304]
### What happened?

the wallpaper does not change when the theme is changed

### Version

3.4

### How did you install Yin & Yang?

Git clone + running install script

### What desktop environments are you seeing the problem on?

KDE

### Which plugin causes the issue?

Wallpaper

### What software version do you use?

KDE 6.0.5

**Comment by tomaz-suller** [comment]
Seems to still be relevant on KDE 6.1.5. Running `yin-yang --toggle` over the terminal we can see the Python traceback

```shell
❯ yin-yang --toggle
Plugin Icons has no support for your desktop environment yet!
Exception in thread Wallpaper:
Traceback (most recent call last):
  File "/usr/lib/python3.12/threading.py", line 1075, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.12/threading.py", line 1012, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/yin-yang/yin_yang/plugins/_plugin.py", line 56, in set_mode
    self.set_theme(theme)
  File "/opt/yin-yang/yin_yang/plugins/_plugin.py", line 208, in set_theme
    self.strategy.set_theme(theme)
  File "/opt/yin-yang/yin_yang/plugins/_plugin.py", line 269, in set_theme
    self.call(self.create_message(theme))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/yin-yang/yin_yang/plugins/wallpaper.py", line 127, in create_message
    message = copy.deepcopy(self.base_message)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/copy.py", line 151, in deepcopy
    rv = reductor(4)
         ^^^^^^^^^^^
TypeError: cannot pickle 'PySide6.QtDBus.QDBusMessage' object
```

Faulty line has been modified in the `beta` branch, so I guess a new release without any modification would fix it? It's also dealt with in #290

**Comment by tomaz-suller** [comment]
Can confirm that installing from the beta version allows you to change the wallpaper
