### ISSUE TITLE
YY run from CLI crashes but GUI is OK

### ISSUE THREAD

**Issue by noyannus** [oskarsh/Yin-Yang#318]
### What happened?

YY, when called from CLI crashes, the GUI (started from launcher) runs OK.

### Version

3.4  latest, built as instructed in README

### How did you install Yin & Yang?

Git clone + running install script

### What desktop environments are you seeing the problem on?

KDE

### Which plugin causes the issue?

None

### Relevant log output

CLI call:
```shell
localhost% yin-yang --debug --systemd
Plugin Icons has no support for your desktop environment yet!
Traceback (most recent call last):
File "<frozen runpy>", line 198, in _run_module_as_main
File "<frozen runpy>", line 88, in _run_code
File "/opt/yin-yang/yin_yang/__main__.py", line 16, in <module>
from yin_yang import daemon_handler
File "/opt/yin-yang/yin_yang/daemon_handler.py", line 7, in <module>
from .config import ConfigWatcher, config
File "/opt/yin-yang/yin_yang/config.py", line 482, in <module>
for pl in filter(lambda pl: pl.available, plugins):
File "/opt/yin-yang/yin_yang/config.py", line 482, in <lambda>
for pl in filter(lambda pl: pl.available, plugins):
^^^^^^^^^^^^
File "/opt/yin-yang/yin_yang/plugins/_plugin.py", line 167, in available
return self.check_command([self.command[0], '--help'])
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/opt/yin-yang/yin_yang/plugins/_plugin.py", line 156, in check_command
subprocess.check_call(command, stdout=subprocess.DEVNULL)
File "/usr/lib64/python3.11/subprocess.py", line 408, in check_call
retcode = call(*popenargs, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib64/python3.11/subprocess.py", line 389, in call
with Popen(*popenargs, **kwargs) as p:
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib64/python3.11/subprocess.py", line 1026, in __init__
self._execute_child(args, executable, preexec_fn, close_fds,
File "/usr/lib64/python3.11/subprocess.py", line 1955, in _execute_child
raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: 'kvantummanager'
```

GUI, started by launcher:
```
# journalctl -b | grep yin-yang
Nov 22 19:15:57 localhost.localdomain yin-yang[275794]: Plugin Icons has no support for your desktop environment yet!
```
```

**Comment by noyannus** [comment]
Forgot the system info.

Operating System: openSUSE Tumbleweed-Slowroll 20241103
KDE Plasma Version: 6.2.3
KDE Frameworks Version: 6.7.0
Qt Version: 6.8.0
Kernel Version: 6.11.6-2-default (64-bit)
Graphics Platform: X11

**Comment by l0drex** [comment]
`yin-yang --debug --systemd` is the command to switch the theme, and it seems to fail to swith the theme from kvantum manager. Do you have that installed? If not, deactivate the plugin (since you are not using it) and try again.

**Comment by l0drex** [comment]
Can you check your config file (`~/.config/yin_yang/yin_yang.json`) if kvantum is enabled somehow?
E.g.
```json
"kvantum": {
    "enabled": true,
    "light_theme": "KvFlatLight",
    "dark_theme": "KvFlat"
},
```

If it is enabled, could you set it to `false` and try again?

**Comment by noyannus** [comment]
There's disabled cruft from long ago... 
```
localhost% cat ~/.config/yin_yang/yin_yang.json
{
"version": 3.4,
"running": false,
"dark_mode": false,
"mode": "manual time",
"coordinates": [
XXXX # they're after me :-)
XXXX
],
"update_location": false,
"update_interval": 60,
"times": [
XXXX
XXXX
],
"boot_offset": 99,
"plugins": {
"system": {
"enabled": true,
"light_theme": "org.kde.breeze.desktop",
"dark_theme": "org.kde.breezedark.desktop"
},

<snip>

"icons": {
"enabled": false,
"light_theme": "",
"dark_theme": ""
},
"kvantum": {
"enabled": false,
"light_theme": "KvFlatLight",
"dark_theme": "KvFlat"
},
"wallpaper": {
"enabled": true,
"light_theme": "/home/me/Pictures/Backgrounds/RGB888888.png",
"dark_theme": "/home/me/Pictures/Backgrounds/RGB222222.png"
},

<snip>

"notification": {
"enabled": false,
"light_theme": "Day",
"dark_theme": "Night"
}
}
}localhost%

```
Deleted the `kvantum` entry. No luck. Does BiT *need* it in the config (`KeyError: 'kvantum'`)?
```

localhost% yin-yang --toggle     # with --systemd it looks the same
Plugin Icons has no support for your desktop environment yet!
Traceback (most recent call last):
File "<frozen runpy>", line 198, in _run_module_as_main
File "<frozen runpy>", line 88, in _run_code
File "/opt/yin-yang/yin_yang/__main__.py", line 16, in <module>
from yin_yang import daemon_handler
File "/opt/yin-yang/yin_yang/daemon_handler.py", line 7, in <module>
from .config import ConfigWatcher, config
File "/opt/yin-yang/yin_yang/config.py", line 477, in <module>
config = ConfigManager()
^^^^^^^^^^^^^^^
File "/opt/yin-yang/yin_yang/config.py", line 163, in __init__
self.load()
File "/opt/yin-yang/yin_yang/config.py", line 235, in load
p.theme_light = config_loaded['plugins'][p.name.lower()]['light_theme']
~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: 'kvantum'
localhost%
```

**Comment by noyannus** [comment]
Well, I lost patience and did a complete reinstall, throwing away all old settings. Now all is fine; it was a false alarm then. 

Thank you for your helpfulness!
