### ISSUE TITLE
Check for installed programs

### ISSUE THREAD

**Issue by FPSUsername** [oskarsh/Yin-Yang#90]
I don't use Firefox and when I try to open yin-yang's settings the app crashes. This is the log when I open it through a terminal:

```python3
Traceback (most recent call last):
  File "/opt/yin-yang/src/gui.py", line 173, in open_settings
    self.secwindow = SettingsWindow()
  File "/opt/yin-yang/src/gui.py", line 24, in __init__
    self.sync_with_config()
  File "/opt/yin-yang/src/gui.py", line 71, in sync_with_config
    widget = plugin.get_widget(self.ui.plugins_scroll_content)
  File "/opt/yin-yang/src/plugins/firefox.py", line 57, in get_widget
    widget = super().get_widget(area)
  File "/opt/yin-yang/src/plugins/_plugin.py", line 90, in get_widget
    for inp in self.get_input(widget):
  File "/opt/yin-yang/src/plugins/_plugin.py", line 99, in get_input
    if self.available_themes != {}:
  File "/opt/yin-yang/src/plugins/firefox.py", line 37, in available_themes
    if not self.available:
  File "/opt/yin-yang/src/plugins/firefox.py", line 54, in available
    return isdir(get_default_profile_path())
  File "/opt/yin-yang/src/plugins/firefox.py", line 17, in get_default_profile_path
    path += config_parser['Profile0']['Path']
  File "/usr/lib/python3.9/configparser.py", line 963, in __getitem__
    raise KeyError(key)
KeyError: 'Profile0'
/usr/bin/yin-yang: line 2: 53718 Aborted                 (core dumped) python3 /opt/yin-yang/main.py $@
```

**Comment by l0drex** [comment]
Oh, makes sense. Should be an easy fix

**Comment by l0drex** [comment]
If you want, you can edit the settings directly in the config file at `~/.config/yin_yang/yin_yang.json` for now.
